/*----List how many distinct albums each singer has.  */
SELECT CONCAT(S.FIRSTNAME, ' ', S.LASTNAME) AS SINGERNAME, 
COUNT(DISTINCT ALBUMNAME) AS total_no_albums
FROM 
PRODUCTS P 
JOIN 
SINGER S
ON
P.SINGER=S.IDSINGER
GROUP BY IDSINGER
ORDER BY SINGERNAME 