/*---List how many products the store has sold for a particular month.--*/

SELECT PRODUCT, 
COUNT(*) AS TOTALNOOFPRODUCTS,
EXTRACT(MONTH FROM PURCHASEDATE) AS MONTH,
monthname(PURCHASEDATE) AS MONTHNAME 
FROM MUSIC_STORE.ORDER ORD
JOIN 
MUSIC_STORE.PRODUCTS PR 
ON
PR.IDPRODUCTS=ORD.PRODUCT
GROUP BY MONTH(PURCHASEDATE)